"use client"

import {
  SectionHeader,
  InfoBox,
  StepFlow,
  ComparisonCards,
  CodeBlock,
  KeyTakeaway,
  NumberedList,
} from "@/components/molecules/article-components"

export function SSGArticleContent() {
  return (
    <div className="prose prose-invert max-w-none">
      <SectionHeader number="01" title="What is Static Site Generation?" />

      <InfoBox type="info">
        SSG pre-renders pages at build time, generating static HTML files that can be cached and served instantly from a
        CDN. This results in the fastest possible page loads and excellent SEO.
      </InfoBox>

      <p className="text-muted-foreground leading-relaxed">
        With SSG, your pages are generated once during the build process. The resulting HTML is then served to every
        user identically, making it perfect for content that doesn{"'"}t change frequently.
      </p>

      <div className="bg-card border border-border rounded-lg p-6 my-8">
        <h4 className="font-semibold text-foreground mb-6">How SSG Works</h4>
        <StepFlow
          steps={[
            { number: 1, title: "Build Time", description: "Pages are rendered to HTML during build" },
            { number: 2, title: "CDN Cache", description: "Static files are distributed globally" },
            { number: 3, title: "Instant Delivery", description: "Users receive pre-built HTML instantly" },
          ]}
        />
      </div>

      <SectionHeader number="02" title="When to Use SSG" />

      <ComparisonCards
        idealTitle="Ideal For"
        notIdealTitle="Not Ideal For"
        idealFor={[
          "Marketing and landing pages",
          "Documentation sites (like this one!)",
          "Blog posts and articles",
          "Product catalogs with infrequent updates",
          "Portfolio and showcase sites",
        ]}
        notIdealFor={[
          "User-specific dashboards",
          "Real-time data displays",
          "Frequently changing content",
          "Personalized experiences",
          "Authentication-dependent content",
        ]}
      />

      <SectionHeader number="03" title="Implementation in Next.js App Router" />

      <InfoBox type="tip">
        In Next.js App Router, pages are statically generated by default when they don{"'"}t use dynamic functions like{" "}
        <code className="bg-muted px-1 rounded">cookies()</code>,{" "}
        <code className="bg-muted px-1 rounded">headers()</code>, or{" "}
        <code className="bg-muted px-1 rounded">searchParams</code>.
      </InfoBox>

      <h3 className="text-xl font-semibold text-foreground mt-8 mb-4">Basic Static Page</h3>
      <p className="text-muted-foreground mb-4">Any page without dynamic data fetching is automatically static:</p>

      <CodeBlock
        title="app/about/page.tsx"
        code={`// This page is automatically statically generated
export default function AboutPage() {
  return (
    <div>
      <h1>About Us</h1>
      <p>This content is generated at build time.</p>
    </div>
  )
}`}
      />

      <h3 className="text-xl font-semibold text-foreground mt-8 mb-4">Static with Data Fetching</h3>
      <p className="text-muted-foreground mb-4">Fetch data at build time with async Server Components:</p>

      <CodeBlock
        title="app/products/page.tsx"
        code={`// Data is fetched at build time
async function getProducts() {
  const res = await fetch('https://api.example.com/products')
  return res.json()
}

export default async function ProductsPage() {
  const products = await getProducts()
  
  return (
    <div>
      {products.map(product => (
        <ProductCard key={product.id} product={product} />
      ))}
    </div>
  )
}`}
      />

      <h3 className="text-xl font-semibold text-foreground mt-8 mb-4">Dynamic Routes with generateStaticParams</h3>
      <p className="text-muted-foreground mb-4">Pre-render dynamic routes at build time:</p>

      <CodeBlock
        title="app/blog/[slug]/page.tsx"
        code={`// Generate static pages for all blog posts
export async function generateStaticParams() {
  const posts = await getPosts()
  
  return posts.map((post) => ({
    slug: post.slug,
  }))
}

export default async function BlogPost({ params }) {
  const { slug } = await params
  const post = await getPostBySlug(slug)
  
  return <article>{post.content}</article>
}`}
      />

      <SectionHeader number="04" title="Benefits of SSG" />

      <NumberedList
        items={[
          {
            title: "Maximum Performance",
            description:
              "Pre-built HTML served directly from CDN edge nodes means the fastest possible Time to First Byte (TTFB).",
          },
          {
            title: "Excellent SEO",
            description:
              "Search engines receive fully-rendered HTML immediately, ensuring all content is crawlable and indexable.",
          },
          {
            title: "Cost Effective",
            description:
              "No server compute required per request. Static files can be served at minimal cost from CDN providers.",
          },
          {
            title: "High Reliability",
            description:
              "Static files rarely fail. No database connections, no server errors, just fast, reliable content delivery.",
          },
          {
            title: "Easy Caching",
            description:
              "CDNs can cache static content indefinitely until the next build, reducing origin server load to zero.",
          },
        ]}
      />

      <SectionHeader number="05" title="Project Reference" />

      <p className="text-muted-foreground leading-relaxed">
        In our electrical services documentation, we use SSG for all documentation pages. Since documentation content
        changes infrequently and is the same for all users, SSG provides the best experience:
      </p>

      <ul className="list-disc list-inside text-muted-foreground space-y-2 my-4">
        <li>
          <strong className="text-foreground">Documentation pages</strong> - Pre-rendered at build time
        </li>
        <li>
          <strong className="text-foreground">Article pages</strong> - Use generateStaticParams for dynamic routes
        </li>
        <li>
          <strong className="text-foreground">Marketing pages</strong> - Static for maximum performance
        </li>
      </ul>

      <KeyTakeaway>
        Use SSG for content that doesn{"'"}t change per-request and is the same for all users. It{"'"}s the fastest,
        most cost-effective, and most reliable rendering strategy available.
      </KeyTakeaway>
    </div>
  )
}
