"use client"

import {
  TableOfContents,
  SectionHeader,
  StepFlow,
  InfoBox,
  KeyTakeaway,
  NumberedList,
  ProcessFlow,
  FeatureGrid,
  ArchitectureDiagram,
  CodeBlock as ArticleCodeBlock,
} from "@/components/molecules/article-components"
import { CodeBlock } from "@/components/atoms/code-block"
import { CodeExplanation } from "@/components/atoms/code-explanation"

export function ErrorBoundariesAndLoadingStatesContent() {
  return (
    <div className="space-y-8">
      <TableOfContents
        items={[
          { id: "problem", title: "Understanding the Problem" },
          { id: "error-tsx", title: "Creating Your First error.tsx" },
          { id: "loading-tsx", title: "Creating Your First loading.tsx" },
          { id: "hierarchy", title: "The File Convention Hierarchy" },
          { id: "recovery", title: "Error Recovery Strategies" },
          { id: "global-error", title: "Global Error Boundary" },
        ]}
      />

      <SectionHeader number="1" title="Understanding the Problem" id="problem" />

      <p className="text-muted-foreground leading-relaxed">
        Without error boundaries, a single failing component crashes the entire page -- users see a white
        screen with no recovery option. Without loading states, route transitions appear frozen. Both
        problems destroy user trust and make your application feel fragile.
      </p>

      <FeatureGrid
        features={[
          {
            title: "Without Error Boundaries",
            description: "Component throws -> entire page goes white -> user must refresh manually",
          },
          {
            title: "With Error Boundaries",
            description: "Component throws -> error UI shows -> user can retry or navigate away",
          },
          {
            title: "Without Loading States",
            description: "User clicks link -> nothing happens for 1-3s -> page appears suddenly",
          },
          {
            title: "With Loading States",
            description: "User clicks link -> skeleton appears instantly -> content streams in",
          },
        ]}
        columns={2}
      />

      <SectionHeader number="2" title="Creating Your First error.tsx" id="error-tsx" />

      <StepFlow
        steps={[
          {
            number: "1",
            title: "Create the file",
            description: "Add error.tsx as a sibling to page.tsx in your route directory",
          },
          {
            number: "2",
            title: "Add 'use client'",
            description: "Error boundaries must be client components (errors are caught client-side)",
          },
          {
            number: "3",
            title: "Accept error and reset props",
            description: "The error object tells you what failed, reset retries the render",
          },
        ]}
      />

      <CodeBlock
        code={`// app/dashboard/error.tsx
"use client"

interface ErrorBoundaryProps {
  error: Error & { digest?: string }
  reset: () => void
}

export default function DashboardError({ error, reset }: ErrorBoundaryProps) {
  return (
    <div className="flex min-h-[400px] flex-col items-center justify-center gap-4">
      <div className="rounded-full bg-destructive/10 p-4">
        {/* Alert icon */}
        <svg className="h-8 w-8 text-destructive" viewBox="0 0 24 24" fill="none" stroke="currentColor">
          <circle cx="12" cy="12" r="10" strokeWidth="2" />
          <line x1="12" y1="8" x2="12" y2="12" strokeWidth="2" />
          <line x1="12" y1="16" x2="12.01" y2="16" strokeWidth="2" />
        </svg>
      </div>

      <h2 className="text-xl font-semibold">Something went wrong</h2>

      <p className="text-muted-foreground text-center max-w-md">
        {error.message || "An unexpected error occurred. Please try again."}
      </p>

      <button
        onClick={reset}
        className="rounded-md bg-primary px-4 py-2 text-primary-foreground"
      >
        Try Again
      </button>

      {error.digest && (
        <p className="text-xs text-muted-foreground">Error ID: {error.digest}</p>
      )}
    </div>
  )
}`}
        language="typescript"
        filename="app/dashboard/error.tsx"
      />

      <CodeExplanation
        summary="error.tsx props explained"
        terms={[
          { term: "error: Error", description: "The JavaScript Error object that was thrown. Contains message and stack trace." },
          { term: "digest?: string", description: "A unique hash of the error generated by Next.js. Useful for matching client errors to server logs." },
          { term: "reset: () => void", description: "Calling this re-renders the route segment, which retries the failed operation. Useful for transient errors like network failures." },
        ]}
      />

      <SectionHeader number="3" title="Creating Your First loading.tsx" id="loading-tsx" />

      <CodeBlock
        code={`// app/dashboard/loading.tsx
// No "use client" needed -- loading.tsx can be a server component
// It should be lightweight and render immediately

export default function DashboardLoading() {
  return (
    <div className="w-full max-w-4xl space-y-6 p-6">
      {/* Header skeleton */}
      <div className="space-y-2">
        <div className="h-8 w-48 animate-pulse rounded bg-muted" />
        <div className="h-4 w-96 animate-pulse rounded bg-muted" />
      </div>

      {/* Content grid skeleton */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {Array.from({ length: 3 }).map((_, i) => (
          <div key={i} className="h-32 animate-pulse rounded-lg bg-muted" />
        ))}
      </div>

      {/* Table skeleton */}
      <div className="space-y-2">
        {Array.from({ length: 5 }).map((_, i) => (
          <div key={i} className="h-12 animate-pulse rounded bg-muted" />
        ))}
      </div>
    </div>
  )
}`}
        language="typescript"
        filename="app/dashboard/loading.tsx"
      />

      <InfoBox type="tip" title="Skeleton vs spinner">
        Skeleton loading states are preferred over spinners because they preview the page structure.
        This reduces perceived loading time and prevents layout shift when real content arrives.
        Match the skeleton layout to your actual page grid and spacing.
      </InfoBox>

      <SectionHeader number="4" title="The File Convention Hierarchy" id="hierarchy" />

      <ArchitectureDiagram
        layers={[
          { label: "layout.tsx", items: ["Wraps everything", "Its errors need a PARENT error.tsx or global-error.tsx"] },
          { label: "loading.tsx", items: ["Suspense boundary", "Shows during data fetching and route transitions"] },
          { label: "error.tsx", items: ["Error boundary", "Catches errors from page.tsx and its children"] },
          { label: "page.tsx", items: ["The actual page content", "Renders inside both loading and error boundaries"] },
        ]}
      />

      <NumberedList
        items={[
          "layout.tsx errors are NOT caught by error.tsx in the same segment -- use a parent error.tsx",
          "loading.tsx shows BEFORE page.tsx mounts, creating instant visual feedback",
          "error.tsx catches errors FROM page.tsx and all its child components",
          "You don't need these files in every route -- place them at meaningful boundaries",
          "Root level (app/error.tsx) acts as the global fallback for the entire application",
        ]}
      />

      <ProcessFlow
        steps={[
          "User navigates to /dashboard",
          "loading.tsx shows skeleton immediately",
          "page.tsx begins rendering (fetching data)",
          "If success: page content replaces skeleton",
          "If error: error.tsx catches and displays recovery UI",
        ]}
        title="Runtime Flow"
      />

      <SectionHeader number="5" title="Error Recovery Strategies" id="recovery" />

      <CodeBlock
        code={`// app/dashboard/error.tsx -- with retry limits
"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"

export default function DashboardError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  const router = useRouter()
  const [retryCount, setRetryCount] = useState(0)
  const maxRetries = 3

  useEffect(() => {
    console.error("[Dashboard Error]", {
      message: error.message,
      digest: error.digest,
      retryCount,
    })
  }, [error, retryCount])

  const canRetry = retryCount < maxRetries

  function handleRetry() {
    if (canRetry) {
      setRetryCount(c => c + 1)
      reset()
    }
  }

  return (
    <div className="flex min-h-[400px] flex-col items-center justify-center gap-4">
      <h2 className="text-xl font-semibold">Something went wrong</h2>
      <p className="text-muted-foreground">{error.message}</p>

      <div className="flex gap-3">
        {canRetry ? (
          <button onClick={handleRetry} className="rounded bg-primary px-4 py-2 text-primary-foreground">
            Try Again ({maxRetries - retryCount} left)
          </button>
        ) : (
          <p className="text-sm text-muted-foreground">Maximum retries reached.</p>
        )}
        <button
          onClick={() => router.push("/dashboard")}
          className="rounded border px-4 py-2"
        >
          Return to Dashboard
        </button>
      </div>
    </div>
  )
}`}
        language="typescript"
        filename="app/dashboard/error.tsx"
      />

      <CodeExplanation
        summary="Recovery pattern explained"
        terms={[
          { term: "retryCount limit", description: "Prevents infinite retry loops. After maxRetries, offer navigation to a safe page." },
          { term: "console.error logging", description: "In production, replace with your monitoring service (Sentry, LogRocket, etc.)" },
          { term: "error.digest", description: "Use this ID in support tickets to match client errors with server-side logs" },
        ]}
      />

      <SectionHeader number="6" title="Global Error Boundary" id="global-error" />

      <InfoBox type="warning" title="global-error.tsx is special">
        Unlike regular error.tsx files, global-error.tsx replaces the ENTIRE HTML document including
        the html and body tags. It must render these elements itself. This is your last line of defence
        when the root layout fails.
      </InfoBox>

      <CodeBlock
        code={`// app/global-error.tsx
"use client"

// global-error.tsx replaces the entire HTML document
// It MUST render <html> and <body> tags

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen items-center justify-center bg-background">
        <div className="text-center space-y-4 p-8">
          <h1 className="text-2xl font-bold">Application Error</h1>
          <p className="text-muted-foreground">
            A critical error occurred. Please refresh the page.
          </p>
          <div className="flex gap-3 justify-center">
            <button
              onClick={reset}
              className="rounded bg-primary px-4 py-2 text-primary-foreground"
            >
              Try Again
            </button>
            <a href="/" className="rounded border px-4 py-2">
              Go Home
            </a>
          </div>
        </div>
      </body>
    </html>
  )
}`}
        language="typescript"
        filename="app/global-error.tsx"
      />

      <StepFlow
        steps={[
          {
            number: "1",
            title: "Add app/error.tsx",
            description: "Root-level fallback for all routes below the root layout",
          },
          {
            number: "2",
            title: "Add app/global-error.tsx",
            description: "Last resort when the root layout itself fails",
          },
          {
            number: "3",
            title: "Add section-level error.tsx",
            description: "Specific handling for major sections like dashboard, admin",
          },
          {
            number: "4",
            title: "Add loading.tsx at navigation boundaries",
            description: "Any route with data fetching or slow imports benefits from a skeleton",
          },
        ]}
      />

      <KeyTakeaway>
        Error boundaries and loading states are not optional polish -- they are core infrastructure.
        Place error.tsx at root and section levels for catch-all protection. Place loading.tsx
        at routes with data fetching. The file convention makes this easy: just create the file
        and Next.js handles the wiring automatically.
      </KeyTakeaway>
    </div>
  )
}
