// Global Molecules - Auto-generated by Phase 2
// Do not edit manually - regenerate with: node scripts/phase2-generate-molecules.js

// Existing molecules
export {
  TableOfContents,
  SectionHeader,
  SubSectionHeader,
  InfoBox,
  StepFlow,
  VerticalFlow,
  ComparisonCards,
  BeforeAfterComparison,
  CodeBlock,
  FileTree,
  ArchitectureDiagram,
  FeatureGrid,
  MetricsGrid,
  DataFlowDiagram,
  DecisionTree,
  KeyTakeaway,
  RelatedArticles,
  StatsTable,
  NumberedList,
  ProcessFlow,
  type TOCItem,
} from "./article-components";
export { ContentCard } from "./content-card";
export { DashboardShell } from "./dashboard-shell";
export { DocPageLayout } from "./doc-page-layout";
export { DocPage } from "./doc-page";
export { DocsSidebar } from "./docs-sidebar";
export { FormNavigation } from "./form-navigation";
export { FormProgressIndicator } from "./form-progress-indicator";
export { FormStepContainer } from "./form-step-container";
export { LocationMapCard } from "./location-map-card";
export { Navbar } from "./navbar";
export { OfficeHoursCard } from "./office-hours-card";
export { QuickContactCard } from "./quick-contact-card";
export { SidebarSkeleton } from "./sidebar-skeleton";
export { StepIndicator } from "./step-indicator";

// New molecules (Phase 2)
export { PlatformHeader } from "./platform-header";
export { BackNavigationCard } from "./back-navigation-card";
export { WhyPlatformCard } from "./why-platform-card";
export { StrategyPhaseCard } from "./strategy-phase-card";
export { ToolCard } from "./tool-card";
export { ReportingCadenceCard } from "./reporting-cadence-card";
export { ContentComparisonTable } from "./content-comparison-table";
