// Global Atoms - Auto-generated by Phase 2
// Do not edit manually - regenerate with: node scripts/phase2-generate-atoms.js

// Existing atoms
export { Callout } from "./callout"
export { CodeBlock } from "./code-block"
export { CodeExplanation } from "./code-explanation"
export { Spoiler } from "./spoiler"

// New atoms (Phase 2)
export { StatusBadge } from "./status-badge"
export { CategoryBadge } from "./category-badge"
export { IconContainer } from "./icon-container"
export { SectionHeading } from "./section-heading"
export { SpecRow } from "./spec-row"
export { ChecklistRow } from "./checklist-row"
export { MetricValue } from "./metric-value"
